#pragma once

#include "core/ASTNode.h"
#include "core/ASTVisitor.h"

#include "nodes/literals/FloatLiteralNode.h"
#include "nodes/literals/IntegerLiteralNode.h"
#include "nodes/literals/StringLiteralNode.h"

#include "nodes/expressions/AssignmentNode.h"
#include "nodes/expressions/BinaryExprNode.h"
#include "nodes/expressions/CallNode.h"
#include "nodes/expressions/FunctionExprNode.h"
#include "nodes/expressions/GoExprNode.h"
#include "nodes/expressions/AwaitExprNode.h"
#include "nodes/expressions/IdentifierNode.h"
#include "nodes/expressions/IndexNode.h"
#include "nodes/expressions/MemberAccessNode.h"
#include "nodes/expressions/UnaryExprNode.h"

#include "nodes/statements/BlockNode.h"
#include "nodes/statements/ExportDeclNode.h"
#include "nodes/statements/IfStatementNode.h"
#include "nodes/statements/ImportDeclNode.h"
#include "nodes/statements/IterNode.h"
#include "nodes/statements/ModuleDeclNode.h"
#include "nodes/statements/PrintNode.h"
#include "nodes/statements/ReturnNode.h"
#include "nodes/statements/UnsafeNode.h"
#include "nodes/statements/WhileStatementNode.h"

#include "nodes/declarations/ActorDeclNode.h"
#include "nodes/declarations/EffectDeclNode.h"
#include "nodes/declarations/EnumDeclNode.h"
#include "nodes/declarations/FunctionDeclNode.h"
#include "nodes/declarations/InterfaceDeclNode.h"
#include "nodes/declarations/StructDeclNode.h"
#include "nodes/declarations/TypeAliasNode.h"
#include "nodes/declarations/VarDeclNode.h"

#include "nodes/runtime/ComptimeNode.h"
#include "nodes/runtime/LeafNode.h"
#include "nodes/runtime/RawNode.h"
#include "nodes/statements/ArrayLiteralNode.h"
#include "nodes/statements/MapLiteralNode.h"
#include "nodes/statements/HandleNode.h"
#include "nodes/statements/TransactionNode.h"
