apiVersion: v1
kind: Service
metadata:
  name: microservicetemplate-app
  namespace: aura-microservicetemplate
spec:
  selector:
    app: microservicetemplate-app
  ports:
    - name: http
      port: 80
      targetPort: 8082
