#pragma once

class IntegerLiteralNode;
class FloatLiteralNode;
class StringLiteralNode;
class IdentifierNode;
class UnaryExprNode;
class BinaryExprNode;
class AssignmentNode;
class VarDeclNode;
class TypeAliasNode;
class StructDeclNode;
class EnumDeclNode;
class InterfaceDeclNode;
class EffectDeclNode;
class ActorDeclNode;
class BlockNode;
class ExportDeclNode;
class IfStatementNode;
class WhileStatementNode;
class FunctionDeclNode;
class FunctionExprNode;
class CallNode;
class GoExprNode;
class AwaitExprNode;
class MemberAccessNode;
class ModuleDeclNode;
class ImportDeclNode;
class ReturnNode;
class PrintNode;
class UnsafeNode;
class ArrayLiteralNode;
class MapLiteralNode;
class IndexNode;
class IterNode;
class TransactionNode;
class HandleNode;
class RawNode;
class LeafNode;
class ComptimeNode;
class ContractNode;

class ASTVisitor
{
public:
	virtual ~ASTVisitor() = default;
	virtual void Visit(IntegerLiteralNode& node) = 0;
	virtual void Visit(FloatLiteralNode& node) = 0;
	virtual void Visit(StringLiteralNode& node) = 0;
	virtual void Visit(IdentifierNode& node) = 0;
	virtual void Visit(UnaryExprNode& node) = 0;
	virtual void Visit(BinaryExprNode& node) = 0;
	virtual void Visit(AssignmentNode& node) = 0;
	virtual void Visit(VarDeclNode& node) = 0;
	virtual void Visit(TypeAliasNode& node) = 0;
	virtual void Visit(StructDeclNode& node) = 0;
	virtual void Visit(EnumDeclNode& node) = 0;
	virtual void Visit(InterfaceDeclNode& node) = 0;
	virtual void Visit(EffectDeclNode& node) = 0;
	virtual void Visit(ActorDeclNode& node) = 0;
	virtual void Visit(BlockNode& node) = 0;
	virtual void Visit(ExportDeclNode& node) = 0;
	virtual void Visit(IfStatementNode& node) = 0;
	virtual void Visit(WhileStatementNode& node) = 0;
	virtual void Visit(FunctionDeclNode& node) = 0;
	virtual void Visit(FunctionExprNode& node) = 0;
	virtual void Visit(CallNode& node) = 0;
	virtual void Visit(GoExprNode& node) = 0;
	virtual void Visit(AwaitExprNode& node) = 0;
	virtual void Visit(MemberAccessNode& node) = 0;
	virtual void Visit(ModuleDeclNode& node) = 0;
	virtual void Visit(ImportDeclNode& node) = 0;
	virtual void Visit(ReturnNode& node) = 0;
	virtual void Visit(PrintNode& node) = 0;
	virtual void Visit(UnsafeNode& node) = 0;
	virtual void Visit(ArrayLiteralNode& node) = 0;
	virtual void Visit(MapLiteralNode& node) = 0;
	virtual void Visit(IndexNode& node) = 0;
	virtual void Visit(IterNode& node) = 0;
	virtual void Visit(TransactionNode& node) = 0;
	virtual void Visit(HandleNode& node) = 0;
	virtual void Visit(LeafNode& node) = 0;
	virtual void Visit(RawNode& node) = 0;
	virtual void Visit(ComptimeNode& node) = 0;
	virtual void Visit(ContractNode& node) = 0;
};
