#pragma once

#include <optional>
#include <string_view>
#include <vector>

namespace Aura::Builtin
{

struct FunctionSpec
{
	std::string_view name;
	std::vector<std::string_view> params;
	std::string_view result;
	bool variadic = false;
	std::optional<std::string_view> variadicParam;
};

struct ModuleSpec
{
	std::string_view name;
	std::vector<FunctionSpec> functions;
	std::string_view sourcePath;
	std::string_view auraSource;
	bool installNativeRuntime = true;
	bool publicImport = true;
};

inline const std::vector<ModuleSpec>& BuiltinModules()
{
	static const std::vector<ModuleSpec> modules = {
		{ "std.memory",
			{
				{ "active_allocations", {}, "int" },
				{ "active_bytes", {}, "int" },
				{ "total_allocations", {}, "int" },
				{ "total_bytes", {}, "int" },
				{ "deep_size", { "any" }, "int" },
				{ "is_send", { "any" }, "bool" },
				{ "is_sync", { "any" }, "bool" },
				{ "assert_send", { "any" }, "bool" },
				{ "assert_sync", { "any" }, "bool" },
				{ "assert_no_leaks", {}, "bool" },
				{ "alloc", { "int" }, "ptr<any>" },
				{ "free", { "any" }, "void" },
			},
			"",
			"",
			false,
			false },
		{ "std.memory_native",
			{
				{ "active_allocations", {}, "int" },
				{ "active_bytes", {}, "int" },
				{ "total_allocations", {}, "int" },
				{ "total_bytes", {}, "int" },
				{ "deep_size", { "any" }, "int" },
				{ "is_send", { "any" }, "bool" },
				{ "is_sync", { "any" }, "bool" },
				{ "assert_send", { "any" }, "bool" },
				{ "assert_sync", { "any" }, "bool" },
				{ "assert_no_leaks", {}, "bool" },
				{ "alloc", { "int" }, "ptr<any>" },
				{ "free", { "any" }, "void" },
			},
			"",
			"",
			true,
			false },
		{ "std.core",
			{
				{ "len", { "[any]" }, "int" },
				{ "max", { "any", "any" }, "any" },
				{ "min", { "any", "any" }, "any" },
				{ "abs", { "any" }, "any" },
				{ "sort", { "[any]" }, "[any]" },
				{ "push", { "[any]", "any" }, "[any]" },
				{ "pop", { "[any]" }, "any" },
				{ "remove", { "[any]", "any" }, "[any]" },
				{ "remove_at", { "[any]", "int" }, "[any]" },
				{ "concat", { "string", "string" }, "string" },
				{ "contains", { "string", "string" }, "bool" },
				{ "to_string", { "any" }, "string" },
				{ "to_int", { "any" }, "int" },
				{ "to_float", { "any" }, "float" },
				{ "to_bool", { "any" }, "bool" },
				{ "clamp", { "any", "any", "any" }, "any" },
			},
			"stdlib/std/core.aura",
			"",
			false,
			true },
		{ "std.core_native",
			{
				{ "len", { "[any]" }, "int" },
				{ "max", { "any", "any" }, "any" },
				{ "min", { "any", "any" }, "any" },
				{ "abs", { "any" }, "any" },
				{ "sort", { "[any]" }, "[any]" },
				{ "push", { "[any]", "any" }, "[any]" },
				{ "pop", { "[any]" }, "any" },
				{ "remove", { "[any]", "any" }, "[any]" },
				{ "remove_at", { "[any]", "int" }, "[any]" },
				{ "concat", { "string", "string" }, "string" },
				{ "contains", { "string", "string" }, "bool" },
				{ "to_string", { "any" }, "string" },
				{ "to_int", { "any" }, "int" },
				{ "to_float", { "any" }, "float" },
				{ "to_bool", { "any" }, "bool" },
				{ "clamp", { "any", "any", "any" }, "any" },
			},
			"",
			"",
			true,
			false },
		{ "std.io",
			{
				{ "print", {}, "void", true, "any" },
				{ "println", {}, "void", true, "any" },
				{ "printf", { "string" }, "void", true, "any" },
				{ "read", {}, "string" },
				{ "readln", {}, "string" },
				{ "read_file", { "string" }, "string" },
			},
			"stdlib/std/io.aura",
			"",
			false,
			true },
		{ "std.io_native",
			{
				{ "print", { "[any]" }, "void" },
				{ "println", { "[any]" }, "void" },
				{ "printf", { "string", "[any]" }, "void" },
				{ "read", {}, "string" },
				{ "readln", {}, "string" },
				{ "read_file", { "string" }, "string" },
			},
			"",
			"",
			true,
			false },
		{ "std.math",
			{
				{ "max", { "any", "any" }, "any" },
				{ "min", { "any", "any" }, "any" },
				{ "abs", { "any" }, "any" },
				{ "clamp", { "any", "any", "any" }, "any" },
			},
			"stdlib/std/math.aura",
			"",
			false,
			true },
		{ "std.array",
			{
				{ "len", { "[any]" }, "int" },
				{ "sort", { "[any]" }, "[any]" },
				{ "push", { "[any]", "any" }, "[any]" },
				{ "pop", { "[any]" }, "any" },
				{ "remove", { "[any]", "any" }, "[any]" },
				{ "remove_at", { "[any]", "int" }, "[any]" },
			},
			"stdlib/std/array.aura",
			"",
			false,
			true },
		{ "std.map",
			{
				{ "new", {}, "map<any,any>" },
				{ "len", { "map<any,any>" }, "int" },
				{ "has", { "map<any,any>", "any" }, "bool" },
				{ "delete", { "map<any,any>", "any" }, "bool" },
				{ "keys", { "map<any,any>" }, "[any]" },
				{ "values", { "map<any,any>" }, "[any]" },
			},
			"stdlib/std/map.aura",
			"",
			false,
			true },
		{ "std.map_native",
			{
				{ "new", {}, "map<any,any>" },
				{ "len", { "map<any,any>" }, "int" },
				{ "has", { "map<any,any>", "any" }, "bool" },
				{ "delete", { "map<any,any>", "any" }, "bool" },
				{ "keys", { "map<any,any>" }, "[any]" },
				{ "values", { "map<any,any>" }, "[any]" },
			},
			"",
			"",
			true,
			false },
		{ "std.base64",
			{
				{ "try_url_decode", { "string" }, "[any]" },
			},
			"stdlib/std/base64.aura",
			"",
			false,
			true },
		{ "std.base64_native",
			{
				{ "try_url_decode", { "string" }, "[any]" },
			},
			"",
			"",
			true,
			false },
		{ "std.crypto",
			{
				{ "hmac_sha256_base64url", { "string", "string" }, "string" },
				{ "constant_time_equal", { "string", "string" }, "bool" },
			},
			"stdlib/std/crypto.aura",
			"",
			false,
			true },
		{ "std.crypto_native",
			{
				{ "hmac_sha256_base64url", { "string", "string" }, "string" },
				{ "constant_time_equal", { "string", "string" }, "bool" },
			},
			"",
			"",
			true,
			false },
		{ "std.text",
			{
				{ "len", { "string" }, "int" },
				{ "concat", { "string", "string" }, "string" },
				{ "contains", { "string", "string" }, "bool" },
				{ "starts_with", { "string", "string" }, "bool" },
				{ "index_of", { "string", "string" }, "int" },
				{ "slice", { "string", "int", "int" }, "string" },
				{ "split", { "string", "string" }, "[string]" },
				{ "to_string", { "any" }, "string" },
				{ "to_int", { "any" }, "int" },
				{ "to_float", { "any" }, "float" },
				{ "to_bool", { "any" }, "bool" },
			},
			"stdlib/std/text.aura",
			"",
			false,
			true },
		{ "std.text_native",
			{
				{ "len", { "string" }, "int" },
				{ "concat", { "string", "string" }, "string" },
				{ "contains", { "string", "string" }, "bool" },
				{ "starts_with", { "string", "string" }, "bool" },
				{ "index_of", { "string", "string" }, "int" },
				{ "slice", { "string", "int", "int" }, "string" },
				{ "split", { "string", "string" }, "[string]" },
				{ "to_string", { "any" }, "string" },
				{ "to_int", { "any" }, "int" },
				{ "to_float", { "any" }, "float" },
				{ "to_bool", { "any" }, "bool" },
			},
			"",
			"",
			true,
			false },
		{ "std.log",
			{
				{ "Error", {}, "void", true, "any" },
				{ "Warn", {}, "void", true, "any" },
				{ "Info", {}, "void", true, "any" },
				{ "Fatal", {}, "void", true, "any" },
			},
			"stdlib/std/log.aura",
			"",
			false,
			true },
		{ "std.log_native",
			{
				{ "Error", { "[any]" }, "void" },
				{ "Warn", { "[any]" }, "void" },
				{ "Info", { "[any]" }, "void" },
				{ "Fatal", { "[any]" }, "void" },
			},
			"",
			"",
			true,
			false },
		{ "std.sync",
			{
				{ "current_thread", {}, "std.sync.Thread" },
				{ "spawn", {}, "std.sync.Thread" },
				{ "mutex", {}, "std.sync.Mutex" },
				{ "lock", { "std.sync.Thread", "std.sync.Mutex" }, "bool" },
				{ "unlock", { "std.sync.Thread", "std.sync.Mutex" }, "bool" },
				{ "join", { "std.sync.Thread", "std.sync.Thread" }, "bool" },
				{ "finish", { "std.sync.Thread" }, "bool" },
			},
			"stdlib/std/sync.aura",
			"",
			false,
			true },
		{ "std.sync_native",
			{
				{ "current_thread", {}, "std.sync.Thread" },
				{ "spawn", {}, "std.sync.Thread" },
				{ "mutex", {}, "std.sync.Mutex" },
				{ "lock", { "std.sync.Thread", "std.sync.Mutex" }, "bool" },
				{ "unlock", { "std.sync.Thread", "std.sync.Mutex" }, "bool" },
				{ "would_deadlock", { "std.sync.Thread", "std.sync.Mutex" }, "bool" },
				{ "assert_no_deadlock", {}, "bool" },
				{ "join", { "std.sync.Thread", "std.sync.Thread" }, "bool" },
				{ "finish", { "std.sync.Thread" }, "bool" },
				{ "is_locked", { "std.sync.Mutex" }, "bool" },
				{ "owner_id", { "std.sync.Mutex" }, "std.sync.Thread" },
				{ "thread_id", { "std.sync.Thread" }, "int" },
				{ "thread_count", {}, "int" },
				{ "mutex_count", {}, "int" },
				{ "wait_edge_count", {}, "int" },
			},
			"",
			"",
			true,
			false },
		{ "std.task",
			{
				{ "spawn", { "any" }, "task<any>", true, "any" },
				{ "join", { "task<any>" }, "any" },
				{ "join_result", { "task<any>" }, "std.result.Result<any, string>" },
				{ "cancel", { "task<any>" }, "bool" },
				{ "is_done", { "task<any>" }, "bool" },
			},
			"stdlib/std/task.aura",
			"",
			false,
			true },
		{ "std.option",
			{},
			"stdlib/std/option.aura",
			"",
			false,
			true },
		{ "std.result",
			{},
			"stdlib/std/result.aura",
			"",
			false,
			true },
		{ "std.task_native",
			{
				{ "go_call", { "any" }, "task<any>", true, "any" },
				{ "join", { "task<any>" }, "any" },
				{ "join_result", { "task<any>" }, "std.result.Result<any, string>" },
				{ "cancel", { "task<any>" }, "bool" },
				{ "is_done", { "task<any>" }, "bool" },
			},
			"",
			"",
			true,
			false },
		{ "std.channel",
			{
				{ "make", { "int" }, "channel<any>" },
				{ "send", { "channel<any>", "any" }, "bool" },
				{ "recv", { "channel<any>" }, "std.option.Option<any>" },
				{ "close", { "channel<any>" }, "bool" },
			},
			"stdlib/std/channel.aura",
			"",
			false,
			true },
		{ "std.channel_native",
			{
				{ "make", { "int" }, "channel<any>" },
				{ "send", { "channel<any>", "any" }, "bool" },
				{ "recv", { "channel<any>" }, "std.option.Option<any>" },
				{ "close", { "channel<any>" }, "bool" },
			},
			"",
			"",
			true,
			false },
		{ "std.concurrent.waitgroup",
			{
				{ "new", {}, "std.concurrent.waitgroup.WaitGroup" },
				{ "add", { "std.concurrent.waitgroup.WaitGroup", "task<void>" }, "void" },
				{ "spawn", { "std.concurrent.waitgroup.WaitGroup", "any" }, "task<void>", true, "any" },
				{ "count", { "std.concurrent.waitgroup.WaitGroup" }, "int" },
				{ "wait", { "std.concurrent.waitgroup.WaitGroup" }, "void" },
			},
			"stdlib/std/concurrent/waitgroup.aura",
			"",
			false,
			true },
		{ "std.concurrent.errorgroup",
			{
				{ "with_context", { "std.context.Context" }, "std.concurrent.errorgroup.ErrorGroup" },
				{ "background", {}, "std.concurrent.errorgroup.ErrorGroup" },
				{ "group_context", { "std.concurrent.errorgroup.ErrorGroup" }, "std.context.Context" },
				{ "add", { "std.concurrent.errorgroup.ErrorGroup", "task<void>" }, "void" },
				{ "spawn", { "std.concurrent.errorgroup.ErrorGroup", "any" }, "task<void>", true, "any" },
				{ "count", { "std.concurrent.errorgroup.ErrorGroup" }, "int" },
				{ "wait", { "std.concurrent.errorgroup.ErrorGroup" }, "std.option.Option<string>" },
			},
			"stdlib/std/concurrent/errorgroup.aura",
			"",
			false,
			true },
		{ "std.context",
			{
				{ "background", {}, "std.context.Context" },
				{ "with_cancel", { "std.context.Context" }, "std.context.Context" },
				{ "cancel", { "std.context.Context" }, "bool" },
				{ "is_cancelled", { "std.context.Context" }, "bool" },
			},
			"stdlib/std/context.aura",
			"",
			false,
			true },
		{ "std.context_native",
			{
				{ "background", {}, "std.context.Context" },
				{ "with_cancel", { "std.context.Context" }, "std.context.Context" },
				{ "cancel", { "std.context.Context" }, "bool" },
				{ "is_cancelled", { "std.context.Context" }, "bool" },
			},
			"",
			"",
			true,
			false },
		{ "std.env",
			{
				{ "get", { "string" }, "string" },
				{ "get_or", { "string", "string" }, "string" },
				{ "has", { "string" }, "bool" },
			},
			"stdlib/std/env.aura",
			"",
			false,
			true },
		{ "std.env_native",
			{
				{ "get", { "string" }, "string" },
				{ "has", { "string" }, "bool" },
			},
			"",
			"",
			true,
			false },
		{ "std.net",
			{
				{ "listen", { "string", "int" }, "std.net.Listener" },
				{ "accept", { "std.net.Listener" }, "std.net.Connection" },
				{ "read", { "std.net.Connection", "int" }, "string" },
				{ "write", { "std.net.Connection", "string" }, "int" },
				{ "close", { "any" }, "bool" },
				{ "local_port", { "any" }, "int" },
				{ "set_nodelay", { "std.net.Connection", "bool" }, "bool" },
				{ "set_read_timeout", { "std.net.Connection", "int" }, "bool" },
				{ "set_write_timeout", { "std.net.Connection", "int" }, "bool" },
			},
			"stdlib/std/net.aura",
			"",
			false,
			true },
		{ "std.net_native",
			{
				{ "listen", { "string", "int" }, "std.net.Listener" },
				{ "accept", { "std.net.Listener" }, "std.net.Connection" },
				{ "read", { "std.net.Connection", "int" }, "string" },
				{ "write", { "std.net.Connection", "string" }, "int" },
				{ "close", { "any" }, "bool" },
				{ "local_port", { "any" }, "int" },
				{ "set_nodelay", { "std.net.Connection", "bool" }, "bool" },
				{ "set_read_timeout", { "std.net.Connection", "int" }, "bool" },
				{ "set_write_timeout", { "std.net.Connection", "int" }, "bool" },
			},
			"",
			"",
			true,
			false },
		{ "std.mysql",
			{
				{ "open", { "string" }, "std.mysql.Connection" },
				{ "open_pool", { "string", "int" }, "std.mysql.Pool" },
				{ "close", { "any" }, "bool" },
				{ "ping", { "any" }, "bool" },
				{ "begin", { "std.mysql.Connection" }, "bool" },
				{ "commit", { "std.mysql.Connection" }, "bool" },
				{ "rollback", { "std.mysql.Connection" }, "bool" },
				{ "exec", { "any", "string" }, "std.mysql.Result" },
				{ "query", { "any", "string" }, "std.mysql.Result" },
				{ "prepare", { "any", "string" }, "std.mysql.Statement" },
				{ "bind", { "std.mysql.Statement", "[any]" }, "std.mysql.Statement" },
				{ "execute", { "std.mysql.Statement" }, "std.mysql.Result" },
				{ "fetch_one", { "std.mysql.Result" }, "std.mysql.Row" },
				{ "fetch_all", { "std.mysql.Result" }, "[std.mysql.Row]" },
				{ "next", { "std.mysql.Result" }, "std.mysql.Row" },
				{ "affected_rows", { "std.mysql.Result" }, "int" },
				{ "last_insert_id", { "std.mysql.Result" }, "int" },
				{ "column_count", { "std.mysql.Result" }, "int" },
				{ "column_name", { "std.mysql.Result", "int" }, "string" },
				{ "get", { "std.mysql.Row", "string" }, "any" },
				{ "get_at", { "std.mysql.Row", "int" }, "any" },
				{ "is_null", { "any" }, "bool" },
				{ "error", { "any" }, "string" },
			},
			"",
			"",
			false,
			false },
		{ "std.mysql_native",
			{
				{ "open", { "string" }, "std.mysql.Connection" },
				{ "open_pool", { "string", "int" }, "std.mysql.Pool" },
				{ "close", { "any" }, "bool" },
				{ "ping", { "any" }, "bool" },
				{ "begin", { "std.mysql.Connection" }, "bool" },
				{ "commit", { "std.mysql.Connection" }, "bool" },
				{ "rollback", { "std.mysql.Connection" }, "bool" },
				{ "with_tx", { "std.mysql.Connection", "any" }, "any" },
				{ "exec", { "any", "string" }, "std.mysql.Result" },
				{ "query", { "any", "string" }, "std.mysql.Result" },
				{ "prepare", { "any", "string" }, "std.mysql.Statement" },
				{ "bind", { "std.mysql.Statement", "[any]" }, "std.mysql.Statement" },
				{ "execute", { "std.mysql.Statement" }, "std.mysql.Result" },
				{ "fetch_one", { "std.mysql.Result" }, "std.mysql.Row" },
				{ "fetch_all", { "std.mysql.Result" }, "[std.mysql.Row]" },
				{ "next", { "std.mysql.Result" }, "std.mysql.Row" },
				{ "affected_rows", { "std.mysql.Result" }, "int" },
				{ "last_insert_id", { "std.mysql.Result" }, "int" },
				{ "column_count", { "std.mysql.Result" }, "int" },
				{ "column_name", { "std.mysql.Result", "int" }, "string" },
				{ "get", { "std.mysql.Row", "string" }, "any" },
				{ "get_at", { "std.mysql.Row", "int" }, "any" },
				{ "is_null", { "any" }, "bool" },
				{ "error", { "any" }, "string" },
			},
			"",
			"",
			true,
			false },
		{ "std.db.mysql",
			{
				{ "open", { "string" }, "std.mysql.Connection" },
				{ "open_pool", { "string", "int" }, "std.mysql.Pool" },
				{ "close", { "any" }, "bool" },
				{ "ping", { "any" }, "bool" },
				{ "begin", { "std.mysql.Connection" }, "bool" },
				{ "commit", { "std.mysql.Connection" }, "bool" },
				{ "rollback", { "std.mysql.Connection" }, "bool" },
				{ "with_tx", { "any", "any" }, "any" },
				{ "query_one", { "any", "string", "[any]" }, "std.mysql.Row" },
				{ "query_all", { "any", "string", "[any]" }, "[std.mysql.Row]" },
				{ "exec_stmt", { "any", "string", "[any]" }, "std.mysql.Result" },
				{ "affected_rows", { "std.mysql.Result" }, "int" },
				{ "last_insert_id", { "std.mysql.Result" }, "int" },
				{ "get", { "std.mysql.Row", "string" }, "any" },
				{ "get_at", { "std.mysql.Row", "int" }, "any" },
				{ "is_null", { "any" }, "bool" },
				{ "error", { "any" }, "string" },
			},
			"stdlib/std/db/mysql.aura",
			"",
			false,
			true },
		{ "std.config",
			{
				{ "get", { "string" }, "string" },
				{ "require", { "string" }, "string" },
				{ "get_int", { "string", "int" }, "int" },
				{ "get_bool", { "string", "bool" }, "bool" },
				{ "get_duration_ms", { "string", "int" }, "int" },
			},
			"stdlib/std/config.aura",
			"",
			false,
			true },
		{ "std.outbox",
			{
				{ "ensure_schema", { "std.mysql.Connection" }, "bool" },
				{ "enqueue_json", { "std.mysql.Connection", "string", "string", "string" }, "int" },
				{ "enqueue_text", { "std.mysql.Connection", "string", "string", "string" }, "int" },
				{ "with_tx", { "std.mysql.Connection", "any" }, "any" },
				{ "run_rabbitmq_relay", { "std.mysql.Connection", "std.mq.rabbitmq.Connection", "int" }, "int" },
				{ "run_rabbitmq_relay_forever", { "std.mysql.Connection", "std.mq.rabbitmq.Connection", "int", "int" }, "void" },
				{ "mark_failed", { "std.mysql.Connection", "int", "string" }, "bool" },
			},
			"stdlib/std/outbox.aura",
			"",
			false,
			true },
		{ "std.backoff",
			{
				{ "constant", { "int" }, "std.backoff.Policy" },
				{ "exponential", { "int", "int", "int" }, "std.backoff.Policy" },
				{ "delay", { "std.backoff.Policy", "int" }, "int" },
				{ "sleep", { "std.backoff.Policy", "int" }, "void" },
				{ "retry", { "int", "std.backoff.Policy", "any" }, "bool" },
			},
			"stdlib/std/backoff.aura",
			"",
			false,
			true },
		{ "std.uuid",
			{
				{ "new_v4", {}, "string" },
			},
			"stdlib/std/uuid.aura",
			"",
			false,
			true },
		{ "std.uuid_native",
			{
				{ "new_v4", {}, "string" },
			},
			"",
			"",
			true,
			false },
		{ "std.http.raw",
			{
				{ "parse_request", { "string" }, "[string]" },
				{ "read_request", { "std.net.Connection" }, "[string]" },
				{ "try_read_request", { "std.net.Connection" }, "[string]" },
				{ "response", { "int", "string", "string" }, "string" },
				{ "response_with_headers", { "int", "string", "string", "[string]" }, "string" },
				{ "text", { "int", "string" }, "string" },
				{ "json", { "int", "string" }, "string" },
				{ "ok_json", { "string" }, "string" },
				{ "redirect", { "string" }, "string" },
			},
			"stdlib/std/http/raw.aura",
			"",
			false,
			true },
		{ "std.http.raw_native",
			{
				{ "parse_request", { "string" }, "[string]" },
				{ "read_request", { "std.net.Connection" }, "[string]" },
				{ "try_read_request", { "std.net.Connection" }, "[string]" },
			},
			"",
			"",
			true,
			false },
		{ "std.http.server_native",
			{
				{ "serve_once", { "string", "int", "([string]) -> string" }, "void" },
				{ "serve_n", { "string", "int", "int", "([string]) -> string" }, "void" },
				{ "listen_and_serve", { "string", "int", "([string]) -> string" }, "void" },
				{ "listen_and_serve_with", { "string", "int", "([string]) -> string", "std.context.Context", "int", "int" }, "void" },
				{ "method", { "std.http.server.Request" }, "string" },
				{ "path", { "std.http.server.Request" }, "string" },
				{ "body", { "std.http.server.Request" }, "string" },
				{ "header", { "std.http.server.Request", "string" }, "string" },
			},
			"",
			"",
			true,
			false },
		{ "std.http.server",
			{},
			"stdlib/std/http/server.aura",
			"",
			false,
			true },
		{ "std.http.middleware",
			{},
			"stdlib/std/http/middleware.aura",
			"",
			false,
			true },
		{ "std.time",
			{
				{ "now_millis", {}, "int" },
				{ "monotonic_nanos", {}, "int" },
				{ "sleep", { "int" }, "void" },
			},
			"stdlib/std/time.aura",
			"",
			false,
			true },
		{ "std.time_native",
			{
				{ "now_millis", {}, "int" },
				{ "monotonic_nanos", {}, "int" },
				{ "sleep", { "int" }, "void" },
			},
			"",
			"",
			true,
			false },
		{ "std.json",
			{
				{ "is_valid", { "string" }, "bool" },
				{ "compact", { "string" }, "string" },
				{ "quote", { "string" }, "string" },
				{ "encode_string", { "string" }, "string" },
				{ "encode_number", { "any" }, "string" },
				{ "encode_bool", { "bool" }, "string" },
				{ "null_literal", {}, "string" },
				{ "field", { "string", "string" }, "string" },
				{ "array", { "[string]" }, "string" },
				{ "object", { "[string]" }, "string" },
				{ "has_key", { "string", "string" }, "bool" },
				{ "get_string", { "string", "string" }, "string" },
				{ "get_int", { "string", "string" }, "int" },
				{ "get_bool", { "string", "string" }, "bool" },
			},
			"stdlib/std/json.aura",
			"",
			false,
			true },
		{ "std.json_native",
			{
				{ "is_valid", { "string" }, "bool" },
				{ "compact", { "string" }, "string" },
				{ "quote", { "string" }, "string" },
				{ "encode_number", { "any" }, "string" },
				{ "has_key", { "string", "string" }, "bool" },
				{ "get_string", { "string", "string" }, "string" },
				{ "get_int", { "string", "string" }, "int" },
				{ "get_bool", { "string", "string" }, "bool" },
			},
			"",
			"",
			true,
			false },
		{ "std.service",
			{
				{ "store_new", {}, "std.service.Store" },
				{ "store_get", { "std.service.Store", "string" }, "string" },
				{ "store_set", { "std.service.Store", "string", "string" }, "int" },
				{ "store_delete", { "std.service.Store", "string" }, "bool" },
				{ "store_len", { "std.service.Store" }, "int" },
				{ "shutdown_context", {}, "std.context.Context" },
				{ "port_or", { "int" }, "int" },
				{ "host_or", { "string" }, "string" },
			},
			"stdlib/std/service.aura",
			"",
			false,
			true },
		{ "std.service_native",
			{
				{ "store_new", {}, "std.service.Store" },
				{ "store_get", { "std.service.Store", "string" }, "string" },
				{ "store_set", { "std.service.Store", "string", "string" }, "int" },
				{ "store_delete", { "std.service.Store", "string" }, "bool" },
				{ "store_len", { "std.service.Store" }, "int" },
				{ "shutdown_context", {}, "std.context.Context" },
			},
			"",
			"",
			true,
			false },
		{ "std.mq.rabbitmq",
			{
				{ "open", { "string" }, "std.mq.rabbitmq.Connection" },
				{ "close", { "std.mq.rabbitmq.Connection" }, "bool" },
				{ "declare_queue", { "std.mq.rabbitmq.Connection", "string" }, "bool" },
				{ "publish", { "std.mq.rabbitmq.Connection", "string", "string" }, "bool" },
				{ "publish_json", { "std.mq.rabbitmq.Connection", "string", "string" }, "bool" },
				{ "consume", { "std.mq.rabbitmq.Connection", "string", "any" }, "void" },
				{ "consume_with_options", { "std.mq.rabbitmq.Connection", "string", "int", "any" }, "void" },
				{ "ack", { "std.mq.rabbitmq.Message" }, "bool" },
				{ "nack", { "std.mq.rabbitmq.Message", "bool" }, "bool" },
				{ "body", { "std.mq.rabbitmq.Message" }, "string" },
				{ "delivery_tag", { "std.mq.rabbitmq.Message" }, "int" },
				{ "routing_key", { "std.mq.rabbitmq.Message" }, "string" },
				{ "error", { "std.mq.rabbitmq.Connection" }, "string" },
			},
			"stdlib/std/mq/rabbitmq.aura",
			"",
			false,
			true },
		{ "std.mq.rabbitmq_native",
			{
				{ "open", { "string" }, "std.mq.rabbitmq.Connection" },
				{ "close", { "std.mq.rabbitmq.Connection" }, "bool" },
				{ "declare_queue", { "std.mq.rabbitmq.Connection", "string" }, "bool" },
				{ "publish", { "std.mq.rabbitmq.Connection", "string", "string" }, "bool" },
				{ "consume", { "std.mq.rabbitmq.Connection", "string", "any" }, "void" },
				{ "consume_with_options", { "std.mq.rabbitmq.Connection", "string", "int", "any" }, "void" },
				{ "ack", { "std.mq.rabbitmq.Message" }, "bool" },
				{ "nack", { "std.mq.rabbitmq.Message", "bool" }, "bool" },
				{ "body", { "std.mq.rabbitmq.Message" }, "string" },
				{ "delivery_tag", { "std.mq.rabbitmq.Message" }, "int" },
				{ "routing_key", { "std.mq.rabbitmq.Message" }, "string" },
				{ "error", { "std.mq.rabbitmq.Connection" }, "string" },
			},
			"",
			"",
			true,
			false },
	};
	return modules;
}

inline const ModuleSpec* FindBuiltinModule(const std::string_view qualifiedName)
{
	for (const auto& module : BuiltinModules())
	{
		if (module.name == qualifiedName)
		{
			return &module;
		}
	}
	return nullptr;
}

inline bool IsBuiltinModuleQualifiedName(const std::string_view qualifiedName)
{
	return FindBuiltinModule(qualifiedName) != nullptr;
}

inline bool IsBuiltinModulePublic(const std::string_view qualifiedName)
{
	const auto* module = FindBuiltinModule(qualifiedName);
	return module && module->publicImport;
}

} // namespace Aura::Builtin
